apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
        run: deployment
    spec:
      containers:
      - name: hello
        image: kennychennetman/hello:v5
        command: ['python', 'app.py']
        ports:
        - containerPort: 80
        env:
          - name: NAME
            valueFrom:
              configMapKeyRef:
                name: hello-env
                key: NAME
          - name: COLOR
            valueFrom:
              configMapKeyRef:
                name: hello-env
                key: COLOR
          - name: VERSION
            valueFrom:
              configMapKeyRef:
                name: hello-env
                key: VERSION
