apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: hello
    version: v3
spec:
  containers:
  - name: hello
    image: kennychennetman/hello:v3
    command: ['python', 'app.py']
